### ISSUE TITLE
对于路径中有. 空格等字符的是不是不支持？

### ISSUE THREAD

**Issue by laycher** [StarLeet/ImageBedMoving#1]
Exception in thread "main" java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near index 3
D:\OneDrive\Laycher's Knowledge Base\01.Blog\vx_images\\w*-?\w*?\.(jpeg|[a-zA-Z]{3})
   ^
        at java.util.regex.Pattern.error(Unknown Source)
        at java.util.regex.Pattern.escape(Unknown Source)
        at java.util.regex.Pattern.atom(Unknown Source)
        at java.util.regex.Pattern.sequence(Unknown Source)
        at java.util.regex.Pattern.expr(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at java.util.regex.Pattern.<init>(Unknown Source)
        at java.util.regex.Pattern.compile(Unknown Source)
        at ImageMoving$PropertiesInfo.loadProperties(ImageMoving.java:86)
        at ImageMoving.main(ImageMoving.java:199)
请按任意键继续. . .

目前在使用中发现如果路径中有. 或者空格等符号的时候，好像不能继续执行。
另外，这个图片只能放到指定的目录下吗？可以放到每个对应md文件同级的vx_images目录下吗？

**Comment by StarLeet** [comment]
不支持是因为我写正则表达式的时候只考虑了image-{数字+字母}这样的组合，或者纯数字+字母。如果你想匹配到带有空格的图片，你可以去修改配置文件内的正则表达式。然后这个程序是扫描当前目录下的md文件，对于子目录是不考虑的。你可以将配置文件内的笔记目录继续切换为子目录。这样就能够在子目录内创建vx_image文件夹了

**Comment by StarLeet** [comment]
如果你会写正则表达式，你可以匹配到所有的，哪怕带空格的图片名。我特意提供了RegStringTest作为正则匹配表达式的测试工具

**Comment by StarLeet** [comment]
路径问题，是java特性决定的。

**Comment by StarLeet** [comment]
> 路径问题，是java特性决定的。

你可以将笔记复制到e下，处理结束后再复制回来

**Comment by laycher** [comment]
你这回复的也太快了吧

**Comment by StarLeet** [comment]
此外，这个程序本身就是将图片迁移到md同级目录内的vx_image。它会直接跳过子目录。

**Comment by laycher** [comment]
只能一个个目录迁移的话，我这有几十个目录和子目录，需要一个个切换了。

**Comment by StarLeet** [comment]
> 你这回复的也太快了吧

具体你可以加我vx，QAQBEE。我可以帮你仔细看

**Comment by StarLeet** [comment]
> 只能一个个目录迁移的话，我这有几十个目录和子目录，需要一个个切换了。

因为遍历整个文件树，需要考虑的因素太多，还要额外记录每个文件所属目录。我在设计之初，只考虑到，一个笔记目录下，应该不会多余10个子目录。

**Comment by StarLeet** [comment]
> 只能一个个目录迁移的话，我这有几十个目录和子目录，需要一个个切换了。

毕竟文件涉及个人重要资料，简化执行，可以提高稳定性，防止数据丢失。

**Comment by laycher** [comment]
> 

感谢！我先研究下！有问题再交流！

**Comment by StarLeet** [comment]
> > 
> 
> 感谢！我先研究下！有问题再交流！

你可以加我vx，QAQBEE。我这个readme确实写的简单了一点。因为后面有事情忙，就只顾写程序，没有更新readme了

**Comment by StarLeet** [comment]
兄弟,今天给你测试了一下.这个项目是支持各类符号的.只不过你的正则写错了
你的正则应该这样写:
ImagesBedPathReg=D:\\\\\\\\OneDrive\\\\\\\\Laycher's Knowledge Base\\\\\\\\01\\\\.Blog\\\\\\\\vx_images\\\\\\\\
ImageNameReg=\\\\w*-?\\\\w*?\\\\.(jpeg|[a-zA-Z]{3})
如果要匹配中文命名的图片,则只需要更改下面的正则即可
